### ISSUE TITLE
error cookie generate

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/yii-web#248]
![image](https://user-images.githubusercontent.com/42547589/80642054-d3d2e380-8a33-11ea-9cc3-29fc6f32a5a1.png)

When generating the cookie, the regex validation fails.

**Comment by samdark** [comment]
Looks like #244. @armpogart would you please take a look?

**Comment by armpogart** [comment]
@terabytesoftw Your cookie value contains invalid characters, specifically `,`(comma). Clients (browser) does not allow comma in cookie value. To overcome that limitation you can simply `urlencode()` your value before passing to `Cookie` constructor. The value will be decoded automatically when parsed from response.

@samdark I have chosen not to `urlencode` cookie value automatically (it was `urlencoded` previously, so that any value was allowed) as in majority cases cookie values do not contain invalid characters and can be passed without any encoding (so without overhead of `urlencode` and also less letters/bytes to pass). But I have documented that in `value` property phpdoc, for further documentation. I am not sure where from OP got that cookie value.

**Comment by armpogart** [comment]
@terabytesoftw One extra question to find out if there is a need for any change/fix.

Where did you get that value from? Did you create any custom cookie or is it maybe from session (PHPSESSID).

@samdark I think it may be from PHPSESSID, if that is the case, I will send a PR with the fix to `urlencode` session id, I have checked php source and php actually allows `,`(comma) in session id, so I think it just automatically `urlencode()`s it, and as we use custom `Session` class which creates a cookie without encoding we encounter this error.

**Comment by terabytesoftw** [comment]
Yes PHPSESSID

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-web/pull/249
