### ISSUE TITLE
Object assigned to a $config key instead plain config

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii-web#39]
https://github.com/yiisoft/yii-web/blob/80116b4dcddce6b6b0ef45be4503c374764c3e9d/tests/UrlRuleTest.php#L241

Why do you assign to 'normalizer' key the object created with $this->factory->create by its configuration?

The configurations should be like this:

```php
        $manager = $this->factory->create([
            '__class' => UrlManager::class,
            'cache' => null,
            'normalizer' => [
                '__class' => UrlNormalizer::class,
                'action' => $normalizerAction,
            ],
        ]);
```

In main/config.php configuration I could not call $this->factory->create in 'normalizer' key.

**Comment by samdark** [comment]
That's specific for tests. What do you want to achieve?

**Comment by FabrizioCaldarelli** [comment]
I thought that was an error during rewriting.

**Comment by hiqsol** [comment]
Good you've noticed it.
If you dive deeper into UrlManager class you'll find that it works with object only, no configuration supported now. Why is it so? That's DI and IoC. I cannot give a good and short explanation here. But there are lots of information on the internet about these techniques.

> In main/config.php configuration I could not call $this->factory->create

And you don't need. Again because of DI.
In a normal application, we need only one properly configured UrlNormalizer and UrlManager. And we put proper DI config.
In tests we need differently configured objects and we pass manually created objects.
